### ISSUE TITLE
Error occurs when compiling the example instrumented source file 

### ISSUE THREAD

**Issue by ye-hongjiang** [drzchen/movec#1]
Hello, I'm reading the paper about this project and I find it interesting. I'd like to try it out but when following the README instructions I got the following errors when compiling the instrumented source file in ```/examples```: 

```
$ movec --check-memsafe -c subobject.c -o output.c
$ gcc output.c 
In file included from output.c:1:
_RV_memsafe.c: In function ‘_RV_has_wrapper’:
_RV_memsafe.c:4759:24: error: ‘_IO_getc’ undeclared (first use in this function)
 4759 |   if(fp == (void (*)())_IO_getc ||
      |                        ^~~~~~~~
_RV_memsafe.c:4759:24: note: each undeclared identifier is reported only once for each function it appears in
_RV_memsafe.c:4760:24: error: ‘_IO_putc’ undeclared (first use in this function)
 4760 |      fp == (void (*)())_IO_putc ||
      |                        ^~~~~~~~
```
Run at Ubuntu 20.04. Compiling the instrumented ```segment.c``` would get the same error.

**Comment by drzchen** [comment]
It seems that the functions _IO_getc and _IO_putc are not supported by your system.
Could you please confirm the issue with the following steps:
(1) Write another small program using _IO_getc and _IO_putc, to check whether they are supported by your system.
(2) Comment the following lines (the equality tests) in the _RV_memsafe.c, to check whether they are supported by your system.
       if(fp == (void (*)())_IO_getc ||
       fp == (void (*)())_IO_putc ||

If (2) works, please leave a message. I can fix the bug in the next version.

**Comment by ye-hongjiang** [comment]
Well, (2) works for me. And actually the following program using ```_IO_putc``` works in my system, too.
```C
#include <stdio.h>

int main () {
   FILE *fp;
   int ch;

   fp = fopen("file.txt", "w");
   for( ch = 33 ; ch <= 100; ch++ ) {
      _IO_putc(ch, fp);
   }
   fclose(fp);
   return(0);
}
```
I'm working with `gcc version 9.3.0 (Ubuntu 9.3.0-17ubuntu1~20.04)` and `build-essential (12.8ubuntu1)`.

**Comment by drzchen** [comment]
Could you please check whether you can put the following code fragment in _RV_memsafe.c into your small program? To see if your system support such comparisons.

if(fp == (void ()())_IO_getc ||
fp == (void ()())_IO_putc ||

**Comment by ye-hongjiang** [comment]
Sorry for the late response. Compiling the following program in my system shows the error:
```C
#include <stdio.h>

int main () {
   FILE *fp;
   if(fp == (void ()())_IO_getc || fp == (void ()())_IO_putc) {}

   int ch;
   fp = fopen("file.txt", "w");
   for( ch = 33 ; ch <= 100; ch++ ) {
      _IO_putc(ch, fp);
   }
   fclose(fp);
   return(0);
}
```
```shell
hongjiang@ubuntu:~/Desktop/code$ gcc test_putc.c 
test_putc.c: In function ‘main’:
test_putc.c:5:24: error: ‘_IO_getc’ undeclared (first use in this function)
    5 |    if(fp == (void ()())_IO_getc || fp == (void ()())_IO_putc) {}
      |                        ^~~~~~~~
test_putc.c:5:24: note: each undeclared identifier is reported only once for each function it appears in
test_putc.c:5:4: error: type name declared as function returning a function
    5 |    if(fp == (void ()())_IO_getc || fp == (void ()())_IO_putc) {}
      |    ^~
test_putc.c:5:53: error: ‘_IO_putc’ undeclared (first use in this function)
    5 |    if(fp == (void ()())_IO_getc || fp == (void ()())_IO_putc) {}
      |                                                     ^~~~~~~~
test_putc.c:5:4: error: type name declared as function returning a function
    5 |    if(fp == (void ()())_IO_getc || fp == (void ()())_IO_putc) {}
      |    ^~
test_putc.c:11:7: warning: implicit declaration of function ‘_IO_putc’ [-Wimplicit-function-declaration]
   11 |       _IO_putc(ch, fp);
      |       ^~~~~~~~
```

**Comment by drzchen** [comment]
Sorry, I think you missed the stars in the parenthesis at Line 5. I mean you may try the following code in your small program.
```
 if(fp == (void (*)())_IO_getc ||
                 ^~~~~~~~ 
    fp == (void (*)())_IO_putc ||
                 ^~~~~~~~
``` 

We expect to fix this bug in the next version.

Another solution is to run Movec on Ubuntu 16.04 (via VM or Docker), since Movec has been extensively tested on Ubuntu 16.04, then copy the generated source code files to Ubuntu 20.04.

**Comment by ye-hongjiang** [comment]
```C
#include <stdio.h>

int main () {
   FILE *fp;
   if(fp == (void (*)())_IO_getc || fp == (void (*)())_IO_putc) {}

   int ch;
   fp = fopen("file.txt", "w");
   for( ch = 33 ; ch <= 100; ch++ ) {
      _IO_putc(ch, fp);
   }
   fclose(fp);
   return(0);
}
```
And the error information is:
```shell
hongjiang@ubuntu:~/Desktop/code$ gcc test_putc.c 
test_putc.c: In function ‘main’:
test_putc.c:5:25: error: ‘_IO_getc’ undeclared (first use in this function)
    5 |    if(fp == (void (*)())_IO_getc || fp == (void (*)())_IO_putc) {}
      |                         ^~~~~~~~
test_putc.c:5:25: note: each undeclared identifier is reported only once for each function it appears in
test_putc.c:5:55: error: ‘_IO_putc’ undeclared (first use in this function)
    5 |    if(fp == (void (*)())_IO_getc || fp == (void (*)())_IO_putc) {}
      |                                                       ^~~~~~~~
test_putc.c:10:7: warning: implicit declaration of function ‘_IO_putc’ [-Wimplicit-function-declaration]
   10 |       _IO_putc(ch, fp);
      |       ^~~~~~~~

```
Anyway I'd close this issue since it looks like just a minor problem related to the version of Ubuntu.
